version: '3.8'
services:
  postgres:
    image: postgres:14.3
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: db-health-managment
    volumes:
      - ./postgres:/var/lib/postgresql/data
