export const DATABASE_ENV_NAMES = {
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USER: 'DB_USER',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_NAME: 'DB_NAME',
};

export const DB_CONNECTIONS = {
  MAIN: 'MAIN',
};
